// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Link: typeof import('./src/components/Link.ts')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
  }
}

export { }
