// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('../src/components/TheFooter.vue')['default'];
    Link: typeof import('./../src/components/Link.ts')['default']
    NavigationBar: typeof import('./../src/components/NavigationBar.vue')['default']
    TheFooter: typeof import('./../src/components/TheFooter.vue')['default']
  }
}

export { }
